---
title: "Data Manipulation"
output: github_document
---
this is the repository for data wrangling 1 part of P8105

```{r setup}
library(tidyverse)
```

## Load in the FAS Litters Data
```{r}
litters_df = read_csv("./data_import_examples/FAS_litters.csv")
litters_df = janitor::clean_names(litters_df)
```

## Select
Choose some columns and not others
```{r}
select(litters_df, group, gd0_weight)
```

```{r}
select(litters_df, group, gd0_weight:gd_of_birth)
```

```{r}
select(litters_df, -litter_number)
```

Renaming columns...
```{r}
select(litters_df, GROUP=group, LITTer_number = litter_number)
```

Select helpers
```{r}
select(litters_df, starts_with("gd"))
```

```{r}
select(litters_df, litter_number, everything())
```

```{r}
relocate(litters_df, litter_number)
```

## Filter
Operates on Rows 

```{r}
filter(litters_df, gd0_weight < 22)
```

```{r}
filter(litters_df, gd_of_birth == 20)
```

```{r}
filter(litters_df, !(gd_of_birth == 20))
```

```{r}
filter(litters_df, gd0_weight >=22, gd_of_birth == 20)
```

```{r}
filter(litters_df, group == "Mod8")
```

```{r}
filter(litters_df, group %in% c("Con7","Mod8"))
```


## Mutate
Modify an existing variable or create new variable

```{r}
# Convert the weight columns to numeric
litters_df <- litters_df %>%
    mutate(gd0_weight = as.numeric(gd0_weight),
           gd18_weight = as.numeric(gd18_weight))
# Create wt_gain column
mutate(litters_df, 
       wt_gain = gd18_weight - gd0_weight,
       group= str_to_lower(group))
```


## Arrange
```{r}
arrange(litters_df, pups_born_alive)
```


## %>%
```{r}
litters_data_raw = read_csv("./data_import_examples/FAS_litters.csv")
litters_clean_name = janitor::clean_names(litters_data_raw)
litters_data_selected = select(litters_clean_name, -pups_survive)
litters_mutated = mutate(litters_data_selected, wt_gain = gd18_weight, gd0_weight)
litters_without_missing = drop_na(litters_mutated, gd0_weight)
```

Use the Pipe operator instead

```{r}
litters_df =
  read_csv("./data_import_examples/FAS_litters.csv") %>% 
  janitor::clean_names() %>% 
  select(-pups_survive) %>% 
  mutate(
    gd18_weight = suppressWarnings(as.numeric(as.character(gd18_weight))),
    gd0_weight = suppressWarnings(as.numeric(as.character(gd0_weight))),
    wt_gain = gd18_weight - gd0_weight
  )

```


